spring:
  ai:
    ollama:
      chat:
        model: gemma3:12b
      init:
        pull-model-strategy: always
        chat:
          additional-models:
            - qwen3:8b
            - deepseek-r1:1.5b
